version: 1.0.{build}

image: Visual Studio 2017

environment:
  configuration: Release
  node_version: "9"

init:
- ps: |
    Install-Product node $env:node_version

before_build:
- ps: |
    cd mjml-aspnetcore
    npm install
    cd ..

build_script:
- ps: |
    cd mjml-aspnetcore
    npm run build
    cd ..

    dotnet build -p:Version=$Env:APPVEYOR_BUILD_VERSION

test_script:
- ps: dotnet test .\test\test.csproj

artifacts:
- path: '**/*.nupkg'
  name: nuget